version: "3.7"

services:
  propertymvt:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    command: >
      sh -c  "python manage.py migrate --noinput &&
              python manage.py runserver 0.0.0.0:8000 &&
              gunicorn arkham.wsgi:application --bind=0.0.0.0:8000 "
    environment:
      DEBUG: 1
    volumes:
      - .:/app
    ports:
      - 8000:8000
    networks:
      - arkham_network

networks:
  arkham_network:
    driver: bridge
